[package]
name = "o2lsh-py"
version = "0.1.0"
authors = ["Michael J. Curry <curry@cs.umd.edu>"]

[dependencies]
pyo3 = "0.2"

[dependencies.o2lsh]
path = ".."

[lib]
name = "o2lsh"
crate-type = ["cdylib"]
